services:
  postgres:
    image: postgres:16
    container_name: rise_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_rise:/var/lib/postgresql/data

  redis:
    image: redis:6.2.14
    container_name: rise_redis
    volumes:
      - redis_data_rise:/data
    ports:
      - '6379:6379'

  backend:
    build: ./
    container_name: rise_backend
    volumes:
      - ./:/app/
      - /app/node_modules
    ports:
      - '5000:5000'
      - '9229:9229'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
      - redis
    env_file: '.env'

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: rise_frontend
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    env_file: '../frontend/.env'
    ports:
      - '3000:3000'

volumes:
  postgres_data_rise:
    driver: local
  redis_data_rise:
    driver: local
