export const PAGES_ROUTES = {
  careerDashboard: '/',
  participant: '/participant',
  compliance: '/compliance',
  policies: '/policies',
  pulseChat: '/pulse-chat',
  policyManagement: '/policy-management',
  calendar: '/calendar',
  login: '/login',
  signup: '/signup',
  verifyEmail: '/verify-email',
  createPassword: 'create-password',
  forgotPassword: 'forgot-password',
  emailTemplate: 'email-template',
};
